--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24.01.2021 12:56:33
-- Server version: 5.7.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gb_php_gallery;

--
-- Drop table `image_count`
--
DROP TABLE IF EXISTS image_count;

--
-- Drop table `image`
--
DROP TABLE IF EXISTS image;

--
-- Set default database
--
USE gb_php_gallery;

--
-- Create table `image`
--
CREATE TABLE image (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `image_count`
--
CREATE TABLE image_count (
  id_count INT(11) NOT NULL,
  count INT(11) DEFAULT NULL,
  PRIMARY KEY (id_count)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE image_count 
  ADD CONSTRAINT FK_image_count_image_id FOREIGN KEY (id_count)
    REFERENCES image(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table image
--
INSERT INTO image VALUES
(1, 'Banksi-1', 3456, 'img/8423_original.png\r\n'),
(2, 'Banksi-2', 456, 'img/artistic-graffiti-26518.jpg'),
(3, 'Banksi-3', 3423, '/img/s1200.jpg'),
(4, 'Banksi-4', 333, '/img/Street-Art-Collection-Banksy-100.jpg');

-- 
-- Dumping data for table image_count
--
INSERT INTO image_count VALUES
(1, 4),
(2, 5),
(3, 2);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;